//! The Rust half of the cross-implementation boot-chain check.
//!
//! The same verdict logic ships twice: here, and in Python in the bootintel.com
//! engine. The reason it ships twice is that a consultancy under an NDA cannot
//! upload a capture and still needs the answer, so `bootintel` decides
//! offline. The risk is that two implementations of one ruleset drift, which
//! would be worse than a bug: the CLI and the dashboard would tell one
//! operator two different things about one board.
//!
//! Neither side is the reference. `tests/fixtures/boot_chain/expect.txt` is,
//! and the engine repo holds a byte-identical copy that its own test
//! (`api/tests/test_boot_chain_parity.py`) asserts against. The file is
//! generated by `scripts/gen-boot-chain-expect.sh` in bootintel.com, which
//! writes both copies in one go. Do not hand-edit it to make this pass: the
//! only thing that makes green meaningful here is that the other repo is
//! reading the same bytes.

use std::fs;
use std::path::PathBuf;

use bootintel_detectors::boot_chain;

fn fixtures() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/boot_chain")
}

/// FNV-1a, matching the generator. Not a security property: it detects a
/// fixture log edited without regenerating the expectation. Chosen because it
/// is eight lines in both languages and adds no dependency to a crate that is
/// deliberately regex-only.
fn fnv1a64(data: &[u8]) -> String {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in data {
        h = (h ^ u64::from(*byte)).wrapping_mul(0x100_0000_01b3);
    }
    format!("{h:016x}")
}

fn field(out: &mut Vec<String>, indent: &str, key: &str, value: &str) {
    if value.is_empty() {
        out.push(format!("{indent}{key}"));
    } else {
        out.push(format!("{indent}{key} {value}"));
    }
}

/// Byte-for-byte the format the Python renderer emits. A plain line format
/// rather than JSON so it diffs cleanly in review, and so this crate needs no
/// serde: it stays serde-free on purpose to keep the CLI binary small.
fn render(name: &str, log: &str) -> Vec<String> {
    let (session, verdicts) = boot_chain::assess(log);
    let mut out = vec![format!(
        "## fixture {name} fnv1a64={}",
        fnv1a64(log.as_bytes())
    )];
    field(
        &mut out,
        "  ",
        "reached",
        if session.reached { "true" } else { "false" },
    );
    field(&mut out, "  ", "evidence", &session.evidence);
    let bytes = match (session.env_used_bytes, session.env_total_bytes) {
        (Some(used), Some(total)) if total > 0 => format!("{used}/{total}"),
        _ => String::new(),
    };
    field(&mut out, "  ", "env_bytes", &bytes);
    for (key, value) in &session.env {
        field(&mut out, "  ", "env", &format!("{key}={value}"));
    }
    for verdict in &verdicts {
        out.push("  verdict".to_string());
        field(&mut out, "    ", "title", &verdict.title);
        field(&mut out, "    ", "state", &verdict.state);
        field(&mut out, "    ", "severity", &verdict.severity);
        field(&mut out, "    ", "evidence", &verdict.evidence);
        field(&mut out, "    ", "detail", &verdict.detail);
        field(
            &mut out,
            "    ",
            "remediation",
            verdict.remediation.as_deref().unwrap_or(""),
        );
    }
    out
}

fn expectation() -> String {
    fs::read_to_string(fixtures().join("expect.txt")).expect("expect.txt is committed")
}

fn declared_fixtures(expected: &str) -> Vec<String> {
    expected
        .lines()
        .filter_map(|l| l.strip_prefix("## fixture "))
        .map(|rest| {
            rest.split_whitespace()
                .next()
                .unwrap_or_default()
                .to_string()
        })
        .collect()
}

#[test]
fn the_cli_reproduces_the_shared_expectation() {
    let expected = expectation();
    let mut lines: Vec<String> = expected
        .lines()
        .filter(|l| l.starts_with('#') && !l.starts_with("##"))
        .map(str::to_string)
        .collect();
    for name in declared_fixtures(&expected) {
        let log = fs::read_to_string(fixtures().join(&name)).expect("fixture is committed");
        lines.extend(render(&name, &log));
    }
    let actual = lines.join("\n") + "\n";
    if actual != expected {
        // Show the first divergence rather than two 200-line blobs.
        let (want, got): (Vec<&str>, Vec<&str>) =
            (expected.lines().collect(), actual.lines().collect());
        let at = want
            .iter()
            .zip(got.iter())
            .position(|(a, b)| a != b)
            .unwrap_or(want.len().min(got.len()));
        panic!(
            "Rust output no longer matches the shared expectation at line {}:\n  \
             expect.txt: {:?}\n  this crate: {:?}\n\nIf the rule changed, regenerate BOTH \
             copies with scripts/gen-boot-chain-expect.sh in bootintel.com. If it did not, \
             the two implementations have drifted.",
            at + 1,
            want.get(at).unwrap_or(&"<end of file>"),
            got.get(at).unwrap_or(&"<end of file>"),
        );
    }
}

#[test]
fn every_fixture_is_pinned_to_its_recorded_hash() {
    let expected = expectation();
    let pins: Vec<&str> = expected
        .lines()
        .filter_map(|l| l.strip_prefix("## fixture "))
        .collect();
    assert!(!pins.is_empty(), "expectation file declares no fixtures");
    for line in pins {
        let mut parts = line.split_whitespace();
        let name = parts.next().expect("fixture name");
        let pin = parts.next().expect("fixture pin");
        let bytes = fs::read(fixtures().join(name)).expect("fixture is committed");
        assert_eq!(
            pin,
            format!("fnv1a64={}", fnv1a64(&bytes)),
            "{name} changed since expect.txt was generated"
        );
    }
}

/// The guard that matters most, and the mirror of the CVE over-matching bug:
/// `KEY=value` lines are everywhere in a boot log, so a careless parser would
/// invent an environment out of a kernel command line and report confident
/// verdicts about a device nobody ever talked to.
#[test]
fn a_plain_boot_log_yields_no_session_and_no_verdict() {
    let plain = "U-Boot 2020.10 (Sep 17 2023 - 11:38:21 +0000)\n\
                 Hit any key to stop autoboot:  2\n\
                 Booting from flash...\n\
                 [    0.000000] Kernel command line: console=ttyS0 root=/dev/mtdblock2\n\
                 CONFIG_FOO=bar\n\
                 PATH=/usr/bin:/bin\n\
                 bootcmd=this is not really an environment\n\
                 [    1.000000] procd: - init -\n";
    let (session, verdicts) = boot_chain::assess(plain);
    assert!(!session.reached, "claimed a shell on a log with no session");
    assert!(
        session.env.is_empty(),
        "invented an environment: {:?}",
        session.env
    );
    assert!(verdicts.is_empty(), "produced verdicts with no session");
}

#[test]
fn an_unterminated_run_of_key_values_is_discarded() {
    // Same shape as a real dump but with no `Environment size:` line, so
    // nothing proves it was one. Absence of proof is not a verdict.
    let log = "bootdelay=3\nbootcmd=bootm 0x82000000\nverify=no\n";
    let (session, verdicts) = boot_chain::assess(log);
    assert!(session.env.is_empty());
    assert!(verdicts.is_empty());
}

/// Absence is reported as unknown, never as good news: U-Boot prints only what
/// is set, so a missing `bootdelay` means the compiled-in default applies and
/// cannot be read from a capture.
#[test]
fn a_missing_variable_is_unknown_rather_than_hardened() {
    let log = "=> printenv\nbootcmd=run sfboot\nEnvironment size: 20/65532 bytes\n";
    let (_, verdicts) = boot_chain::assess(log);
    let delay = verdicts
        .iter()
        .find(|v| v.title == "Autoboot delay")
        .expect("an absent bootdelay still gets a verdict");
    assert_eq!(delay.state, "unknown");
    assert_eq!(delay.evidence, "bootdelay absent");
    assert!(verdicts.iter().all(|v| v.state != "hardened"));
}

#[test]
fn a_wrapped_value_is_rejoined_rather_than_ending_the_dump() {
    let log = fs::read_to_string(fixtures().join("wrapped-env.log")).expect("fixture");
    let (session, _) = boot_chain::assess(&log);
    let upfw = session
        .env
        .get("upfw")
        .expect("the wrapped variable survived");
    assert!(
        upfw.ends_with("${filesize};"),
        "continuation line was dropped: {upfw}"
    );
    // And the variable AFTER the wrap is still there, which is what a
    // boundary-on-continuation bug would have eaten.
    assert!(session.env.contains_key("upbootldr"));
}

#[test]
fn every_verdict_names_the_variable_it_read() {
    // A consultant has to defend the answer in a client report rather than
    // quote a tool, so an unevidenced verdict is a broken one.
    for name in declared_fixtures(&expectation()) {
        let log = fs::read_to_string(fixtures().join(&name)).expect("fixture");
        for verdict in boot_chain::verdict(&boot_chain::parse_session(&log)) {
            assert!(
                !verdict.evidence.trim().is_empty(),
                "{name}: {:?} has no evidence",
                verdict.title
            );
            assert!(
                ["confirmed", "exposed", "hardened", "unknown"].contains(&verdict.state.as_str()),
                "{name}: {:?} has state {:?}",
                verdict.title,
                verdict.state
            );
        }
    }
}
